### ISSUE TITLE
Some Quality

### ISSUE THREAD

**Issue by cw-peter** [jjperezaguinaga/the-giftening#1]
![under-the-bus](https://cloud.githubusercontent.com/assets/9445267/7831087/867904cc-0453-11e5-99b8-ba387cd9322c.gif)
![fire](https://cloud.githubusercontent.com/assets/9445267/7831091/8c27e348-0453-11e5-8ae6-7ec807a9eea8.gif)
![it-begins](https://cloud.githubusercontent.com/assets/9445267/7831092/925d2b60-0453-11e5-8ba8-6b0b45e9e734.gif)
![as-you-wish](https://cloud.githubusercontent.com/assets/9445267/7831093/979b64fc-0453-11e5-943d-bc2d7364e084.gif)
![55441766](https://cloud.githubusercontent.com/assets/9445267/7831098/9c50df5e-0453-11e5-8466-12ac3ddc9a17.jpg)

**Comment by cw-peter** [comment]
![no-idea](https://cloud.githubusercontent.com/assets/9445267/7831103/b2d13332-0453-11e5-974d-80c95098e4fc.gif)
![anigif_fun-fun-fun-29834-1300112565-20](https://cloud.githubusercontent.com/assets/9445267/7831107/b6d3064a-0453-11e5-9c33-e611e3afe828.gif)
![200](https://cloud.githubusercontent.com/assets/9445267/7831111/bcbd85b2-0453-11e5-96c3-521aedbbf798.gif)
![tumblr_m5kbumtppi1r777xho1_500](https://cloud.githubusercontent.com/assets/9445267/7831112/c27c3da4-0453-11e5-91bb-169d02567d7f.gif)
![giphy-1](https://cloud.githubusercontent.com/assets/9445267/7831116/c68a0bf6-0453-11e5-98cd-c0ea3686e630.gif)

**Comment by 0xjjpa** [comment]
PR yo.

**Comment by cw-peter** [comment]
![mind_blown](https://cloud.githubusercontent.com/assets/9445267/7831126/e6c9944a-0453-11e5-9cbf-1835bf8472dc.gif)
![giphy-3](https://cloud.githubusercontent.com/assets/9445267/7831127/e9acf792-0453-11e5-9351-ab084deb3ffd.gif)
![Uploading thats-terrifying.gif…]()
![tumblr_n2ukm980jv1tw5bhko1_500](https://cloud.githubusercontent.com/assets/9445267/7831132/f3448e6e-0453-11e5-81ff-51caf80e7fb5.gif)
![im-done](https://cloud.githubusercontent.com/assets/9445267/7831134/f63ad128-0453-11e5-96e9-1094b6c61965.gif)
![giphy-4](https://cloud.githubusercontent.com/assets/9445267/7831137/f9a32a5e-0453-11e5-9a96-7d0ed4e04e82.gif)
![lol_ricky_gervais](https://cloud.githubusercontent.com/assets/9445267/7831139/fc88d91c-0453-11e5-8135-00548adfa936.gif)

**Comment by cw-peter** [comment]
![df2dfhs](https://cloud.githubusercontent.com/assets/9445267/7831144/0e32729a-0454-11e5-9aab-d7c74130759c.gif)
![nope](https://cloud.githubusercontent.com/assets/9445267/7831147/113fec1a-0454-11e5-840b-873eee6370a6.gif)
![tumblr_inline_n8ihisakao1s22o6k](https://cloud.githubusercontent.com/assets/9445267/7831148/13ee1ae0-0454-11e5-91cc-d1a89133737d.gif)

![200-2](https://cloud.githubusercontent.com/assets/9445267/7831150/16a231a4-0454-11e5-81a0-09fd52513647.gif)
![ylfdg3u](https://cloud.githubusercontent.com/assets/9445267/7831151/1ac73cac-0454-11e5-9834-b621a765b089.gif)
![tumblr_inline_nfirl87sls1raprkq](https://cloud.githubusercontent.com/assets/9445267/7831153/1e7a0c08-0454-11e5-9cd6-005480417881.gif)
![i-regret-nothing](https://cloud.githubusercontent.com/assets/9445267/7831155/2557e748-0454-11e5-9137-f6f64186b6be.gif)

**Comment by 0xjjpa** [comment]
Added. Closing
![Nice](http://media.tumblr.com/tumblr_lmg562CJ1Y1qzcrvj.gif)
